# CommandGuard config.yml
#=====-----=====-----=====-----[      Categories      ]-----=====-----=====-----=====#
# Each category must have a unique identifier. For example: bank or factions or whatever.
# Each category has separate region,command,and error message.
# If blacklist:false, the worlds list is treated as a whitelist.
#
# For example, the bank commands below only used in regions named BankRegion and ATMRegion
#

category:
  # example:
  #   blacklist: false
  #   regions:
  #   - "ExampleSpawnRegion"
  #   commands:
  #   - "spawn"
  #    messages:
  #    - '&e&l(!) &cCan''t Use That Command in This Region'
  #    - '&e&l(!) &cYou Must Go To &6Safe Zone &cFirst!'
  #    sounds:
  #    - "ENTITY_BLAZE_DEATH"
  bank:
    blacklist: false
    worldguard-regions:
    - "BankRegion"
    - "ATMRegion"
    residence-regions: []
    commands:
      # Exact - block exact what is set if i set ban Gasha then ONLY /ban Gasha will be blocked if i prevent "ban" then only /ban will be prevented but not /ban Gasha
      exact: []
      # Ignore args - block set command and everything after it all arguments example if i prevent ban , they won't be able to type /ban neither /ban Gasha or any other name
      # Note: as the list name suggests, you can't put args in it
      ignore-args:
        - "bank"
      # Starts with - block commands that starts with any of the listed strings
      # In this case, example of blocked commands: "withdraw Gasha", "withdraw Gasha 100" "withdraw GashaPlayer123 1"
      starts-with:
        - "withdraw Gasha"
    messages:
    - '&e&l(!) &cCan''t Use That Command in This Region'
    - '&e&l(!) &cYou Must Go To &6Bank &cFirst!'
    sounds:
    - "ENTITY_BLAZE_DEATH"
  teleport:
    blacklist: true
    worldguard-regions:
      - "NoTpRegion"
    residence-regions: []
    commands:
      exact:
        - "tphere Gasha"
      ignore-args: []
      starts-with:
        - "tp Gasha"
    messages:
    - '&e&l(!) &cCan''t Use That Command in This Region'
    - '&e&l(!) &cPeople in the &6Bank &cShould not teleport!'
    sounds:
    - "ENTITY_BLAZE_DEATH"

# Prevent Plugin Sniffing
# This Feature need Protocollibs to work
# Fake Plugin displayed when player use /version [TAB]
fake-plugins: "CoolWarp, CoolSpawn, CoolEconomy"